# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NotificationDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NotificationDemo

	pod 'Firebase/Analytics'
 
    pod 'Firebase/Messaging'
    pod "youtube-ios-player-helper"

  target 'NotificationDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NotificationDemoUITests' do
    # Pods for testing
  end
 

end
